#Basic python3 runtime
runtime: python
runtime_config:
  python_version: 3

#Application
env: standard
version: 0
default_expiration: "7d"
skip_files:
  -test_data/
  -README.md

#Handlers
handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
