application: nn4mc-web
api_version: 1
env: standard
version: 0

runtime: python
runtime_config:
  python_version: 3

threadsafe: false

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: main.app
